// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf5AQYYIGp1-yDk5CqIHQ098rVI-rjBko',
    appId: '1:293710142649:web:edc6a81dd6818ced0e0f68',
    messagingSenderId: '293710142649',
    projectId: 'moblifytesting',
    authDomain: 'moblifytesting.firebaseapp.com',
    storageBucket: 'moblifytesting.appspot.com',
    measurementId: 'G-XN2L2YZD2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnojBbhOj8q45AgIipsfDdncs8fOC4kRU',
    appId: '1:293710142649:android:b00e9374033c0bde0e0f68',
    messagingSenderId: '293710142649',
    projectId: 'moblifytesting',
    storageBucket: 'moblifytesting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtkhfSLvXOb4fCpQlUGXtreNo4Bcam1Zo',
    appId: '1:293710142649:ios:bfaee415e6199c100e0f68',
    messagingSenderId: '293710142649',
    projectId: 'moblifytesting',
    storageBucket: 'moblifytesting.appspot.com',
    iosBundleId: 'com.example.theme1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtkhfSLvXOb4fCpQlUGXtreNo4Bcam1Zo',
    appId: '1:293710142649:ios:a3d5713ec986ce6f0e0f68',
    messagingSenderId: '293710142649',
    projectId: 'moblifytesting',
    storageBucket: 'moblifytesting.appspot.com',
    iosBundleId: 'com.example.theme1.RunnerTests',
  );
}
