// enum Block_Name { // Views {
//   // ButtomBarBlock,
//   Image_Banner_Slider_Block,
//   Scrolling_Text_Block,
//   Collection_Grid_Block,
//   Product_Grid_Block,
//   Count_Down_Timer_Block,
//   Testimonials_Block,
//   Image_Banner_Block,
  
//   Divider_Block,
//   Instagram_Feed_Block,
//   Icon_Text_Block,
//   Video_Block,
//   Search_Block,
//   Comparison_Block,
//   Discount_Section_Block,

//   // BannerImageView,
//   // BannerTextView,
//   // BannerTextSubtitle,
//   // BannerButtonTextView,
//   // BannerVideoView,
//   // FAQView,
//   // BlogView,
//   // ProductView,
//   // CategoryView,
//   // TextTileView,
//   // SocialMediaLink,
//   // GridView,
//   // WebView
// }